# Generated by Django 2.2.1 on 2019-06-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='cert_num',
            new_name='certification_number',
        ),
    ]
